#!/bin/bash
#
# Command-Line tool to create backups and rotate them.

### --- VARIABLES --- ###

PROGRAM_NAME="$(basename $0)"
CONFIG_DIR="config"
LIB_DIR="lib"

### --- FUNCTIONS --- ###

# err throws a error text in red to stderr,
# accompanied by the passed arguments.
err()
{
  echo -e " \033[31m[ERR] [$(date +'%Y-%m-%dT%H:%M:%S%z')]: $*\033[0m" >&2
}

# import_sources_from_dir sources the passed
# filepaths into the environment.
import_sources_from_dir()
{
	local target_dir="${1}"

	for file in "$target_dir"/*; do

		if [[ -f "$file" ]]; then
			source "$file"
		fi

	done
}

### --- MAIN CODE --- ###

## Initial sourcing
for target_dir in "$CONFIG_DIR" "$LIB_DIR"; do
	import_sources_from_dir "$target_dir"
done

## Initial Validation
if ! validate_dirs "$BACKUP_SOURCE_DIR" "$BACKUP_TARGET_DIR"; then
	err "Some directories are not valid"
	exit 1
fi

## Create Backup
if ! main_archive_already_exists; then

	create_backup

else

	if theres_new_data; then

		make_rotation

	fi

fi