#!/bin/bash
#
# Command-Line tool to create backup and rotate them

### --- VARIABLES --- ###

config_dir="config"
lib_dir="lib"

### --- FUNCTIONS --- ###

err()
{
  echo -e "\033[31m[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $*\033[0m" >&2
}

import_sources_from_dir()
{
	local target_dir="${1}"

	for file in "$target_dir"/*; do

		if [[ -f "$file" ]]; then
			echo "Sourcing $file"
			source "$file"
		fi

	done
}

### --- MAIN CODE --- ###

## Initial sourcing
for target_dir in "$config_dir" "$lib_dir"; do
	import_sources_from_dir "$target_dir"
done

## Initial Validation
if ! validate_dirs "$BACKUP_SOURCE_DIR" "$BACKUP_TARGET_DIR"; then
	err "Some directories are not valid"
	exit 1
fi

## Create Backup
if theres_new_data; then

	if main_archive_already_exists; then

		echo "Doing Rotation..."
		make_rotation

	fi

	echo "Making backup"
	create_backup

else

	echo "No new data to backup"

fi